version: '3.1'

services:
  redis:
    image: redis:alpine
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
    driver: local
